### ISSUE TITLE
It might be better if the font can be changed by user

### ISSUE THREAD

**Issue by geckour** [DroidKaigi/conference-app-2024#577]
In my opinion, the current font of the app (`dot_gothic16_regular.ttf`) is a little difficult to read smoothly.
So, how about that allow user to toggle fonts between the current used one and more uncharacteristic one (like Noto) ?

**Comment by Corvus400** [comment]
I would like to work on this issue. 🙋‍♂️

**Comment by Corvus400** [comment]
@geckour @takahirom 
I am thinking of going ahead with a font change UI like the attached video, what do you think?
I think it would be difficult to notice if it is added to an item on the About screen.
How about adding it to the TopAppBar of the Timetable screen, which is the first place people will see it, so that it is easy to notice?

https://github.com/user-attachments/assets/90989125-2a08-432d-b03d-7f238486a838

**Comment by takahirom** [comment]
I would prefer to have a setting in the 'About' section or somewhere similar. The timetable screen is an important feature, and we don't want users to be distracted. We might need to have a settings screen that can be accessed from the 'About' screen.
