### ISSUE TITLE
Close the keyboard when tapping outside the text input field and keyboard on the profile screen

### ISSUE THREAD

**Issue by Yamada-Ika** [DroidKaigi/conference-app-2024#594]
Currently, the keyboard cannot be closed except by swiping left. It is likely preferable to have the behavior described in the title.

https://github.com/user-attachments/assets/674410f6-b913-411f-b06b-3ed481d3c495

**Comment by Nagumo-7960** [comment]
I would like to work on this task🙋‍♂️

**Comment by Yamada-Ika** [comment]
@Nagumo-7960 Thanks! Assigned!

**Comment by Corvus400** [comment]
@Nagumo-7960 @Yamada-Ika @takahirom 
Sorry, this issue is quite a barrier to working on the Composable Multiplatform task right now. 🙇 
(Because you cannot close the keyboard on the iPhone, you cannot proceed from the Edit screen to the Card screen.)
If you don't mind, I'd like to quickly address it on my end. 🙇

**Comment by Nagumo-7960** [comment]
@Corvus400 

Sorry for the delay in resolving the issue, I'll leave it to you🙇‍♂️

**Comment by takahirom** [comment]
I'm not sure about this issue but I've changed the assign 🙏

**Comment by Corvus400** [comment]
@takahirom 
Since it took so long to build the actual machine that I could not take a video, I will explain only in writing.
In the simulator, if you focus on EditText and type text from the keyboard, the keyboard does not rise up from the bottom, so you can press the create button.
However, when I tap EditText on the actual iPhone device, the keyboard remains raised up, so I cannot press the compose button.
So, I cannot create a ProfileCard, which interferes with other tasks.

**Comment by takahirom** [comment]
> However, when I tap EditText on the actual iPhone device, the keyboard remains raised up, so I cannot press the compose button.
So, I cannot create a ProfileCard, which interferes with other tasks.

I understand. Thank you for building apps for devices. 🙇
