### ISSUE TITLE
Scrolling up and down repeatedly on SponsorsScreen redraws the logo

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#628]
## Overview
As the title suggests, the sponsor logo seems to redraw when scrolling.

https://github.com/user-attachments/assets/6fc3c6b3-343b-4c0b-b4b5-b8b3719c8ac0

## Solutions I can come up with
The following places are no longer redrawn when `AsyncImage` is used, but I do not know why they are redrawn when using `rememberAsyncImagePainter` in coil3 and not when `AsyncImage` is used...

https://github.com/DroidKaigi/conference-app-2024/blob/ba0e875c2cd1e6de9179e2744baf71b54e7d0e06/feature/sponsors/src/commonMain/kotlin/io/github/droidkaigi/confsched/sponsors/component/SponsorItem.kt#L38-L40

👇

```kotlin
        AsyncImage(
            model = sponsor.logo,
           ...
```

https://github.com/user-attachments/assets/c1b0565e-fc48-4614-b8fc-b48434799b1d

**Comment by ked4ma** [comment]
the coid's document says
- rememberAsyncImagePainter is a lower-level API that may **not** behave as expected in all cases.
- **If you need a Painter and can't use AsyncImage**, you can load the image using rememberAsyncImagePainter

https://coil-kt.github.io/coil/compose/#asyncimagepainter

Is it better to change to use `AsyncImage` instead of `rememberAsyncImagePainter` as much as possible at other codes?
https://github.com/search?q=repo%3ADroidKaigi%2Fconference-app-2024%20painter%20%3D%20rememberAsyncImagePainter&type=code

**Comment by ked4ma** [comment]
I found related issue at [conference-app-2023](https://github.com/DroidKaigi/conference-app-2023/issues/1088). (ref: https://github.com/coil-kt/coil/issues/1610)
And in above issue, it says the cause may be large size logo images.

from coil 3.0.0-alpha10, we can set maxBitmapSize to ImageLoader and ImageRequest (like followings)
```
    val imageLoader = remember {
        ImageLoader.Builder(platformContext)
            .maxBitmapSize(Size(360, 360)) <---- [here]
            .build()
    }
```
when use `maxBitmapSize`, image loading speed was little bit faster actually but rendering behavior was almost same...

|before|after|
|--|--|
|<video src="https://github.com/user-attachments/assets/576f4e8c-e974-479d-873b-87a99948cab2" width=300/>|<video src="https://github.com/user-attachments/assets/dae5fedb-1cb4-4ec9-b9ea-2ae3e0001d3e" width=300/>|

So I would like to make a pr with `AsyncImage` for SponsorScreen as written in description :pray:
