### ISSUE TITLE
In EditScreen, vertical padding of CreateButton is narrow

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#771]
## Overview
As the title says, the vertical padding of Create Card Button is narrow.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/1ac8eee4-012b-4b37-8b11-d6869a747268" width="300">|<img src="https://github.com/user-attachments/assets/334279fc-0d0c-4c4f-ab3c-f30b6515100a" width="300">|

## Figma
https://www.figma.com/design/XUk8WMbKCeIdWD5cz9P9JC/DroidKaigi-2024-App-UI?node-id=55588-34615&t=VpbDVe3CvbfpqvxU-4

**Comment by Songgyubin** [comment]
:raising_hand: I want to try it!

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by Songgyubin** [comment]
@takahirom 
I have something to report.
The padding between the Image label and the Add Image button is wider than that of Figma.
I have identified the cause of the problem. Is it okay to handle it together while dealing with the above issue?

## Screenshot
Figma | Actual
:--: | :--:
<image src="https://github.com/user-attachments/assets/f293c633-0e61-4beb-ab09-de210db907b3" width="300" /> |<image src="https://github.com/user-attachments/assets/ae3850e5-2a2c-4da6-9eef-6e06e6d63cd6" width="300" />

**Comment by takahirom** [comment]
@Songgyubin I think it's ok to handle! Thank you for your reporting

**Comment by Songgyubin** [comment]
@kosenda @takahirom 
Would it be alright if we go over this one more time?

Is it correct that the issue is that the vertical padding of the Create Card button on the actual screen is wider than that of the Create Card button in Figma?

However, looking at the code, the vertical padding is narrower than that of the Figma.
`figma vertical padding: 18dp / actual padding: 16dp`

Maybe the vertical padding value looks different because of the Android phone system font size?

cf.1)
**Figma**
figma's top padding: 18dp
<image src="https://github.com/user-attachments/assets/cc54d9b4-f6b5-4d0d-a7b7-deb0a958e0d8" width="500" />

**Actual Code**
8dp(Text's Padding) + 8dp(Button's default content padding) = 16dp
<image src="https://github.com/user-attachments/assets/91c6d638-2d5d-498b-9959-1dfe3bb99753" width="500" />

```kotlin
 Button(
                onClick = {
                    onClickCreate(
                        ProfileCard.Exists(
                            nickname = nickname,
                            occupation = occupation,
                            link = link,
                            image = imageByteArray?.toBase64() ?: "",
                            cardType = selectedCardType,
                        ),
                    )
                },
                enabled = isValidInputs,
                modifier = Modifier.fillMaxWidth()
                    .testTag(ProfileCardCreateButtonTestTag),
            ) {
                Text(
                    modifier = Modifier.padding(8.dp),
                    text = stringResource(ProfileCardRes.string.create_card),
                )
            }
```
cf.2)
**Buttons for each system font size**
<image src="https://github.com/user-attachments/assets/c6beb14b-ee86-4fbb-b421-0317c688df1e" width="300" /> |<image src="https://github.com/user-attachments/assets/7109ca4e-eaeb-4d30-8607-133a0640a484" width="300" /> |<image src="https://github.com/user-attachments/assets/23c3e3fb-c31f-42fa-86bc-7b8bfa3f12a2" width="300" /> |<image src="https://github.com/user-attachments/assets/d69ec1ab-b30d-40b8-b33a-8bdae2c93388" width="300" />

**Comment by Songgyubin** [comment]
@takahirom 
Additionally, the padding is different between Select Thme Item and Create Card.

Can I handle this too?

## Screenshot
Figma | Actual
:--: | :--:
<image src="https://github.com/user-attachments/assets/815f9206-2362-4260-9eea-d2d5ac64dd57" width="300" /> |<image src="https://github.com/user-attachments/assets/2c5e35c0-e6e1-4187-984c-4c9372c3e5c0" width="300" />

**Comment by kosenda** [comment]
@Songgyubin cc: @takahirom 
Sorry for the lack of explanation 🙇
This issue was intended to be about the padding outside the button, not the padding around the text inside the button!
(Both the top and bottom of the padding outside the button are narrow)

**Comment by Songgyubin** [comment]
@kosenda  cc: @takahirom 
it's okay. I should have asked in more detail before starting work :)

So I guess that's what this comment is about.

I will request `PR` after the work is in progress.

thank you for your reply.

> @takahirom 또한, Select Thme Item과 Create Card 사이의 패딩이 다릅니다.
> 
> 제가 이걸 처리할 수 있을까요?
> 
> ## 스크린샷
> 피그마	실제
> <img alt="" width="300" src="https://github.com/user-attachments/assets/815f9206-2362-4260-9eea-d2d5ac64dd57">	<img alt="" width="300" src="https://github.com/user-attachments/assets/2c5e35c0-e6e1-4187-984c-4c9372c3e5c0">
