### ISSUE TITLE
TimetableGridItem speaker's Text overflow handling is different from Figma

### ISSUE THREAD

**Issue by kosenda** [DroidKaigi/conference-app-2024#894]
## Overview
I think Ellipsis is correct for the Speaker of TimetableGridItem for one line and TextOverflow when looking at Figma.

|Figma|Actual|
|---|---|
|<img src="https://github.com/user-attachments/assets/c2ed5f88-4ea6-4101-afc9-56e1e9c1e00c" width="300">|<img src="https://github.com/user-attachments/assets/7d77e3c8-aa8d-4112-93cf-c960f59a20db" width="300">|

**Comment by s-kamada** [comment]
🙋 
I wanna handle this!

**Comment by takahirom** [comment]
Thanks! Assigned 👍

**Comment by s-kamada** [comment]
The number of lines in the session title also seems to be different. (Figma has 3 lines, actual has 2 lines).
I will try to handle the issue of the number of lines in the title together.

**Comment by s-kamada** [comment]
As I commented earlier, I was going to fix the number of lines in the session title together, but there seems to be a problem with the [logic used to calculate the height of the text in the session title](https://github.com/DroidKaigi/conference-app-2024/blob/7b153b56db624975ba19b599a52a373e4b16d255/feature/sessions/src/commonMain/kotlin/io/github/droidkaigi/confsched/sessions/component/TimetableGridItem.kt#L333). (Because simple fixes such as maxLines and weight were not enough to solve the problem.)
Therefore, I will create another Issue regarding the number of lines in the session title.
